/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoeventospostgres.vista;

import com.mycompany.proyectoeventospostgres.controlador.KPIRentabilidadCtrl;
import com.mycompany.proyectoeventospostgres.modelo.KPIRentabilidadModel;

import javax.swing.*;

/**
 *
 * @author Charly Cimino
 */
public class KPIRentabilidadView extends javax.swing.JFrame {

    /**
     * Creates new form KPIRentabilidadView
     */

    private KPIRentabilidadCtrl kPIRentabilidadCtrl;
    private KPIRentabilidadModel kPIRentabilidadModel;
    public KPIRentabilidadView() {
        kPIRentabilidadCtrl = new KPIRentabilidadCtrl(this);
        kPIRentabilidadModel = new KPIRentabilidadModel();
        initComponents();

        //cargar datos a las tablas
        kPIRentabilidadModel.comisionAgentes(jTablePKI2);
        kPIRentabilidadModel.inmueblesMasRentados(jTablePKI3);
        kPIRentabilidadModel.kpiInmobilaria(gananciaTotal, jlCantidadArriendos, jlPromedioComision, jlPrimerArriendo, jlUltimoArriendo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKPI1 = new javax.swing.JButton();
        btnKPI2 = new javax.swing.JButton();
        btnKPI3 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gananciaTotal = new javax.swing.JLabel();
        jlCantidadArriendos = new javax.swing.JLabel();
        jlPromedioComision = new javax.swing.JLabel();
        jlPrimerArriendo = new javax.swing.JLabel();
        jlUltimoArriendo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePKI2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePKI3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnKPI1.setText("kpi inmobilaria");
        btnKPI1.addActionListener(kPIRentabilidadCtrl);

        btnKPI2.setText("Comision agente");
        btnKPI2.addActionListener(kPIRentabilidadCtrl);

        btnKPI3.setText("inmuebles mas arrendados");
        btnKPI3.addActionListener(kPIRentabilidadCtrl);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(kPIRentabilidadCtrl);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("selecccione");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir)
                            .addComponent(btnKPI3)
                            .addComponent(btnKPI2)
                            .addComponent(btnKPI1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKPI1)
                .addGap(60, 60, 60)
                .addComponent(btnKPI2)
                .addGap(65, 65, 65)
                .addComponent(btnKPI3)
                .addGap(116, 116, 116)
                .addComponent(btnSalir)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 528));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("📊  Bienvenido al Panel de KPIs de la Inmobiliaria");

        gananciaTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gananciaTotal.setText("Ganancia total");
        gananciaTotal.setToolTipText("");
        gananciaTotal.setBorder(new javax.swing.border.MatteBorder(null));
        gananciaTotal.setFocusable(false);
        gananciaTotal.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jlCantidadArriendos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCantidadArriendos.setText("Cantidad de arriendos");
        jlCantidadArriendos.setBorder(new javax.swing.border.MatteBorder(null));

        jlPromedioComision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlPromedioComision.setText("Promedio Comisión");
        jlPromedioComision.setBorder(new javax.swing.border.MatteBorder(null));

        jlPrimerArriendo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlPrimerArriendo.setText("Primer arriendo");
        jlPrimerArriendo.setBorder(new javax.swing.border.MatteBorder(null));

        jlUltimoArriendo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUltimoArriendo.setText("Último arreindo");
        jlUltimoArriendo.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUltimoArriendo)
                    .addComponent(jlPrimerArriendo)
                    .addComponent(jlPromedioComision)
                    .addComponent(jlCantidadArriendos)
                    .addComponent(gananciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(gananciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jlCantidadArriendos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jlPromedioComision, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jlPrimerArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jlUltimoArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jTablePKI2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePKI2);

        jLabel8.setText("kpi2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel8)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jTablePKI3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePKI3);

        jLabel9.setText("kpi3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel9)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, -36, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //getters and setters


    public JButton getBtnKPI1() {
        return btnKPI1;
    }

    public void setBtnKPI1(JButton btnKPI1) {
        this.btnKPI1 = btnKPI1;
    }

    public JButton getBtnKPI2() {
        return btnKPI2;
    }

    public void setBtnKPI2(JButton btnKPI2) {
        this.btnKPI2 = btnKPI2;
    }

    public JButton getBtnKPI3() {
        return btnKPI3;
    }

    public void setBtnKPI3(JButton btnKPI3) {
        this.btnKPI3 = btnKPI3;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getGananciaTotal() {
        return gananciaTotal;
    }

    public void setGananciaTotal(JLabel gananciaTotal) {
        this.gananciaTotal = gananciaTotal;
    }

    public JLabel getJlCantidadArriendos() {
        return jlCantidadArriendos;
    }

    public void setJlCantidadArriendos(JLabel jlCantidadArriendos) {
        this.jlCantidadArriendos = jlCantidadArriendos;
    }

    public JLabel getJlPromedioComision() {
        return jlPromedioComision;
    }

    public void setJlPromedioComision(JLabel jlPromedioComision) {
        this.jlPromedioComision = jlPromedioComision;
    }

    public JLabel getJlPrimerArriendo() {
        return jlPrimerArriendo;
    }

    public void setJlPrimerArriendo(JLabel jlPrimerArriendo) {
        this.jlPrimerArriendo = jlPrimerArriendo;
    }

    public JLabel getJlUltimoArriendo() {
        return jlUltimoArriendo;
    }

    public void setJlUltimoArriendo(JLabel jlUltimoArriendo) {
        this.jlUltimoArriendo = jlUltimoArriendo;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTable getjTablePKI2() {
        return jTablePKI2;
    }

    public void setjTablePKI2(JTable jTablePKI2) {
        this.jTablePKI2 = jTablePKI2;
    }

    public JTable getjTablePKI3() {
        return jTablePKI3;
    }

    public void setjTablePKI3(JTable jTablePKI3) {
        this.jTablePKI3 = jTablePKI3;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KPIRentabilidadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KPIRentabilidadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KPIRentabilidadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KPIRentabilidadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KPIRentabilidadView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKPI1;
    private javax.swing.JButton btnKPI2;
    private javax.swing.JButton btnKPI3;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel gananciaTotal;
    private javax.swing.JLabel jlCantidadArriendos;
    private javax.swing.JLabel jlPromedioComision;
    private javax.swing.JLabel jlPrimerArriendo;
    private javax.swing.JLabel jlUltimoArriendo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePKI2;
    private javax.swing.JTable jTablePKI3;
    // End of variables declaration//GEN-END:variables
}
